inherit: 
    - ../model_sweep/model3.yaml
    - wandb.yaml

model:
    n_dims: 2
    n_positions: 101

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 2
            end: 2
            inc: 0
            interval: 101
